### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by llrs** [Bioconductor/biocblog#13]
I recently realize that Bioconductor doesn't appear in the frequent feeds about R I follow.
This blog might be a good way to share updates with the R community. 

I was not able to find an RSS feed of the blog. 
I'm not sure if it needs to be [set up](https://rstudio.github.io/distill/blog.html#rss-feed) or there is a special url where this is present.
If an RSS feed is created people could follow the updates of Bioconductor. 
Additionally some app could be used to automate the posting to other services (twitter, R bloggers, ...).

**Comment by kozo2** [comment]
Thank you for your suggestion @llrs !
I added the RSS feed to https://bioconductor.github.io/biocblog/ !

![image](https://user-images.githubusercontent.com/12192/183382285-d945c993-cd4b-41e2-a4fc-426083161057.png)

Let me know if it doesn't work!

**Comment by llrs** [comment]
The current feed provides the description, but some feeds, like R-bloggers needs the full post.
I think it is enough for my use case (I might add it to the account of [R_dev_news](https://twitter.com/R_dev_news/ in twitter).

**Comment by lcolladotor** [comment]
Hm... https://bioconductor.github.io/biocblog/index.xml does seem to include the full blog post now. I didn't check before. Dunno if @kozo2 changed a setting to enable this. It's also valid according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbioconductor.github.io%2Fbiocblog%2Findex.xml+ 

If you submit the above URL to https://www.r-bloggers.com/add-your-blog/ and ... hm... Rweekly changed. I don't see at https://rweekly.org/submit how to submit the RSS feed anymore. Though I do see at https://rweekly.org/about the link to the RSS feed validator https://validator.w3.org/feed/

**Comment by llrs** [comment]
Maybe I misunderstood what the description field is.

**Comment by kozo2** [comment]
I checked that the RSS https://bioconductor.github.io/biocblog/index.xml works fine with Thunderbird.
I close this issue.
