### ISSUE TITLE
Use package canonical URLs

### ISSUE THREAD

**Issue by hpages** [Bioconductor/biocblog#36]
Hi @mblue9, @stemangiola ,

Please note that publications should preferrably use the _package canonical URL_ (a.k.a. _package short URL_) to link to a Bioconductor package.

So for example, in the CuratedAtlasQueryR post, things like `[cellxgenedp](https://bioconductor.org/packages/release/bioc/html/cellxgenedp.html)` and `[SingleCellExperiment](https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html)` should be replaced with `[cellxgenedp](https://bioconductor.org/packages/cellxgenedp)` and `[SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment)`.

Also the same should probably be done for **CuratedAtlasQueryR** once the package gets added to Bioconductor.

The reason for this is that the _package canonical URL_ is the only URL that we are committed to keep around forever. There's no such guarantee with other URLs, and they are actually likely to break at some point in the future when we refactor our website.

Thanks,
H.

**Comment by mblue9** [comment]
Thanks for that information @hpages I did not know that. I will change those URLs in the post.
